// Données des groupes

export const groupsData = [
  // MIGRATOIRE
  {
    id: 1,
    contentText: "Migratoire",
    nestedGroups: [11, 12, 13],
    showNested: true,
    className: "vert",
    order: 1,
  },
  {
    id: 11,
    contentText: "Statut résidentiel",
    nestedInGroup: 1,
    dependsOn: 12,
    className: "line_11",
    order: 1,
    showGaps: true,
    showOverlaps: true,
  },
  {
    id: 12,
    contentText: "Logement",
    nestedInGroup: 1,
    dependsOn: 13,
    className: "line_12",
    order: 2,
    showGaps: true,
    showOverlaps: true,
  },
  {
    id: 13,
    contentText: "Commune",
    nestedInGroup: 1,
    className: "line_13",
    order: 3,
    showGaps: true,
    showOverlaps: true,
  },
  // Familiale
  {
    id: 2,
    contentText: "Familiale",
    nestedGroups: [21, 22, 23],
    showNested: false,
    className: "bleu",
    order: 2,
  },
  {
    id: 21,
    contentText: "Etat matrimoniale",
    nestedInGroup: 2,
    className: "line_21",
    order: 1,
    showGaps: false,
    showOverlaps: false,
  },
  {
    id: 22,
    contentText: "Enfants",
    nestedInGroup: 2,
    className: "line_22",
    order: 2,
    showGaps: false,
    showOverlaps: false,
  },
  {
    id: 23,
    contentText: "Composition ménage",
    nestedInGroup: 2,
    dependsOn: [21, 22],
    className: "line_23",
    order: 3,
    showGaps: false,
    showOverlaps: false,
  },

  // SCOLAIRE
  {
    id: 3,
    contentText: "Scolaire",
    nestedGroups: [31, 32],
    showNested: false,
    className: "jaune",
    order: 3,
  },
  {
    id: 31,
    contentText: "Niveau",
    nestedInGroup: 3,
    className: "line_31",
    order: 1,
    showGaps: false,
    showOverlaps: false,
  },
  {
    id: 32,
    contentText: "Type",
    nestedInGroup: 3,
    dependsOn: 31,
    className: "line_32",
    order: 2,
    showGaps: false,
    showOverlaps: false,
  },

  // PROFESSIONNELLE
  {
    id: 4,
    contentText: "Professionnelle",
    nestedGroups: [41, 42, 43, 44],
    showNested: false,
    className: "rouge",
    order: 4,
  },
  {
    id: 41,
    contentText: "Status d'activité",
    nestedInGroup: 4,
    className: "line_41",
    order: 1,
    showGaps: false,
    showOverlaps: false,
  },
  {
    id: 42,
    contentText: "Profession",
    nestedInGroup: 4,
    dependsOn: 41,
    className: "line_42",
    order: 2,
    showGaps: false,
    showOverlaps: false,
  },
  {
    id: 43,
    contentText: "Secteur",
    nestedInGroup: 4,
    dependsOn: 42,
    className: "line_43",
    order: 3,
    showGaps: false,
    showOverlaps: false,
  },
  {
    id: 44,
    contentText: "Lieu",
    nestedInGroup: 4,
    dependsOn: 42,
    className: "line_44",
    order: 4,
    showGaps: false,
    showOverlaps: false,
  },
];
